name: CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * 5"

jobs:
  plugin_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:

      # - name: setup_asdf
      #   uses: asdf-vm/actions/plugin-test@v1.0.0

      # - name: setup_openpgp_team_keyring
      #   run: ./bin/import-release-team-keyring

      # - name: asdf_plugin_test
      #   env:
      #     GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: node --version

      # - name: setup_openpgp_team_keyring
      #   uses: asdf-vm/actions/plugin-test@v1.0.0
      #   with:
      #     command: ./bin/import-release-team-keyring
          
      - name: asdf_plugin_test
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: |
            ./bin/import-release-team-keyring && \
            node --version